apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki-helm.querier-frontend" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier-frontend
spec:
  minReadySeconds: 10
  replicas: {{ .Values.querierFrontend.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: querier-frontend
  template:
    metadata:
      annotations:
        config_hash: 8f80031113ab434770ef7e9215512968
      labels: {{- include "loki-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: querier-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 16 }}
                app.kubernetes.io/component: querier-frontend
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/overrides/overrides.yaml
        - -log.level=debug
        - -target=query-frontend
        image: {{ .Values.loki.image }}
        imagePullPolicy: {{ .Values.loki.pullPolicy | quote }}
        name: query-frontend
        {{- if .Values.querierFrontend.env }}
        env: {{- toYaml .Values.querierFrontend.env | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 3100
          name: http-metrics
        - containerPort: 9095
          name: grpc
        {{- if .Values.querierFrontend.resources }}
        resources: {{- toYaml .Values.querierFrontend.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/loki/config
          name: loki
        - mountPath: /etc/loki/overrides
          name: overrides
        {{- with .Values.querierFrontend.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - configMap:
          name: {{ include "loki-helm.fullname" . }}-config
        name: loki
      - configMap:
          name: {{ include "loki-helm.fullname" . }}-overrides
        name: overrides
      {{- with .Values.querierFrontend.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
