apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-helm.querier" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
spec:
  ports:
  - name: querier-http-metrics
    port: 3100
    targetPort: 3100
  - name: querier-grpc
    port: 9095
    targetPort: 9095
  {{- if .Values.memberlist.enable }}
  - name: querier-memberlist
    port: {{ .Values.memberlist.port}}
    targetPort: {{ .Values.memberlist.port}}
  {{- end }}
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: querier
