apiVersion: v2
name: gitlab-extra-exporter
description: A Helm chart to deploy [gitlab-extra-exporter](https://github.com/Whyeasy/gitlab-extra-exporter)
type: application
version: 0.1.10
appVersion: 0.0.9
