apiVersion: v1
data:
  config.yaml: |
    auth_enabled: false
    chunk_store_config:
        chunk_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: {{ include "loki-helm.memcached" . }}.{{ .Release.Namespace }}.svc.cluster.local
                service: memcached-client
        max_look_back_period: {{ .Values.storage.config.retentionPeriod }}
        write_dedupe_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: {{ include "loki-helm.memcached-index-writes" . }}.{{ .Release.Namespace }}.svc.cluster.local
                service: memcached-client
    distributor:
        ring:
            kvstore:
                consul:
                    consistent_reads: false
                    host: {{ include "loki-helm.consul" . }}.{{ .Release.Namespace }}.svc.cluster.local:8500
                    http_client_timeout: 20s
                    watch_burst_size: 1
                    watch_rate_limit: 1
                store: consul
    frontend:
        compress_responses: {{ .Values.querierFrontend.config.compressResponses }}
        max_outstanding_per_tenant: 200
        {{- if .Values.querierFrontend.config.logQueries}}
        log_queries_longer_than: {{ .Values.querierFrontend.config.logQueries }}
        {{- end }}
    frontend_worker:
        frontend_address: {{ include "loki-helm.querier-frontend" . }}.{{ .Release.Namespace }}.svc.cluster.local:9095
        grpc_client_config:
            max_send_msg_size: 1.048576e+08
        parallelism: {{ .Values.querier.config.parallelism }}
    ingester:
        chunk_block_size: {{ .Values.ingester.config.chunkSize }}
        chunk_idle_period: {{ .Values.ingester.config.chunkIdle }}
        chunk_target_size: {{ .Values.ingester.config.chunkTargetSize }}
        max_chunk_age: {{ .Values.ingester.config.maxChunkAge }}
        lifecycler:
            claim_on_rollout: true
            heartbeat_period: 5s
            interface_names:
              - eth0
            join_after: 30s
            num_tokens: 512
            ring:
                heartbeat_timeout: 1m
                kvstore:
                    consul:
                        consistent_reads: true
                        host: {{ include "loki-helm.consul" . }}.{{ .Release.Namespace }}.svc.cluster.local:8500
                        http_client_timeout: 20s
                    store: consul
                replication_factor: {{ .Values.ingester.config.replicationFactor }}
        max_transfer_retries: {{ .Values.ingester.config.transferRetries }}
    ingester_client:
        grpc_client_config:
            max_recv_msg_size: 6.7108864e+07
        remote_timeout: 1s
    limits_config:
        enforce_metric_name: false
        ingestion_burst_size_mb: 20
        ingestion_rate_mb: 10
        ingestion_rate_strategy: global
        max_global_streams_per_user: 10000
        max_query_length: 12000h
        max_query_parallelism: 32
        max_streams_per_user: 0
        reject_old_samples: true
        reject_old_samples_max_age: 168h
    query_range:
        align_queries_with_step: true
        cache_results: {{ .Values.querierFrontend.config.cacheResult }}
        max_retries: 5
        results_cache:
            cache:
                memcached_client:
                    consistent_hash: true
                    host: {{ include "loki-helm.memcached-frontend" . }}.{{ .Release.Namespace }}.svc.cluster.local
                    max_idle_conns: 16
                    service: memcached-client
                    timeout: 500ms
                    update_interval: 1m
            max_freshness: 10m
        split_queries_by_interval: {{ .Values.querierFrontend.config.splitQueries }}
    schema_config:
        configs:
          - from: "2018-04-15"
            index:
                period: 168h
                prefix: monitoring_index_
            object_store: {{ .Values.storage.objectStore }}
            schema: v11
            store: {{ .Values.storage.store }}
    server:
        graceful_shutdown_timeout: 5s
        grpc_server_max_concurrent_streams: 1000
        grpc_server_max_recv_msg_size: 1.048576e+08
        grpc_server_max_send_msg_size: 1.048576e+08
        http_listen_port: 3100
        http_server_idle_timeout: 120s
        http_server_write_timeout: 1m
    storage_config:
        cassandra:
            addresses: {{ .Values.storage.config.storeUrl }}
            auth: false
            keyspace: lokiindex
            replication_factor: {{ .Values.storage.config.replicationFactor }}
        gcs:
            bucket_name: {{ .Values.storage.config.bucketName }}
        index_queries_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: {{ include "loki-helm.memcached-index-queries" . }}.{{ .Release.Namespace }}.svc.cluster.local
                service: memcached-client         
    table_manager:
        chunk_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        index_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        retention_deletes_enabled: {{ .Values.storage.config.retentionDelete }}
        retention_period: {{ .Values.storage.config.retentionPeriod }}
kind: ConfigMap
metadata:
  name: {{ include "loki-helm.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki-config
